import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from './components/header/header';
import { Container } from './components/container/container';
import { Footer } from './components/footer/footer';
import { SectionContainer } from './components/container/section-container';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Gadget Daddy',
  description: 'Generated by you know who',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <Container>
          <SectionContainer>{children}</SectionContainer>
        </Container>
        <Footer />
      </body>
    </html>
  );
}
