import { IMenu } from '../../interfaces';

export const menu: IMenu[] = [
  {
    id: '1',
    name: 'Phones',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [
      { id: '1', name: 'Apple', isActive: true, isDeleted: false, isPopular: false },
      { id: '2', name: 'Samsung', isActive: true, isDeleted: false, isPopular: false },
    ],
  },
  {
    id: '2',
    name: 'Laptops',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [
      { id: '1', name: 'Macbook', isActive: true, isDeleted: false, isPopular: false },
      { id: '2', name: 'Surface', isActive: true, isDeleted: false, isPopular: false },
    ],
  },
  {
    id: '3',
    name: 'Tablets',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '4',
    name: 'Desktops',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [
      { id: '1', name: 'Macbook', isActive: true, isDeleted: false, isPopular: false },
      { id: '2', name: 'Surface', isActive: true, isDeleted: false, isPopular: false },
    ],
  },
  {
    id: '5',
    name: 'Accessories',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '6',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '7',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '8',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '9',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '10',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '11',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '12',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '13',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
  {
    id: '14',
    name: 'Gaming',
    isActive: true,
    isDeleted: false,
    isPopular: false,
    brands: [],
  },
];
